### ISSUE TITLE
Cutcode history table in settings

### ISSUE THREAD

**Issue by Ethicmeta** [studenton/cutcode#23]
The last 'n' cutcode copy pastes in a table with a date. Updates date value if the same code is added, otherwise new line. Once max count is reached, drop the oldest.

**Comment by andrewmbyrd** [comment]
Hello, I am new to OSS, but I'd like to help on this project if possible!

I've noted in recent updates to Chrome, it is desirable to have the options for any extension to pop up as a modal in the extensions page. Developers can still manually link to a separate tab for options, however.

Is the aim to have this table with code snippets and dates appear in the options page, or somewhere else?

**Comment by kot91** [comment]
For the sake of space it might be relevant to have a link in the options modal to a new tab for the table to be located. Because the code that was copied might be significant in length, we should limit the displayed amount to n characters and they can click a button to display the entire code block in modal view. 

I think it would also be a great idea to have the source url as an additional column regardless if the user chooses to use attribution. Gives context to the data they are using (each url can be a hyperlink!)

**Comment by andrewmbyrd** [comment]
Alright, sounds good I'll set to work on it!

**Comment by andrewmbyrd** [comment]
I've uploaded my work to my own repo - [here](https://github.com/andrewmbyrd/cutcode/tree/dev).

A few things to note:

 - In order to persist the data, the only way I could find without adding files to the user's hard drive or requiring them to have a google drive account was to use the [chrome.storage.sync API](https://developer.chrome.com/extensions/storage#property-sync). Of note, that storage is quite limited in it's capacity(it's mainly used to store _only_ option settings). I found that it broke after the snippet history exceeded around 6500-7000 characters, so that drove me to set max characters for any one snippet entry to 500, and I have a default of 12 snippets max in the history.

- It seems that there is no way to load up the history in the options tab without also including it in the options modal. [options API](https://developer.chrome.com/extensions/optionsV2). Actually it is possible now, but the documentations says it will break in a future release. Still, the table looks quite nice in the modal.

-You can configure the options in the new Options hyperlink that appears in the Google Extensions main page

Feel free to check that everything looks good on your machine. If it does, let me know and I'll submit the pull request!

**Comment by kot91** [comment]
Hey andrew, I recommend checking out pr #19 and trying to implement the browser detection, found specifically in the settings/settings.js file! I'd love to check these out once that is implemented as i use firefox.

**Comment by andrewmbyrd** [comment]
Ah, I tend to be a Chrome user myself! I updated it to use a different Storage Area. I tested on my Windows machine on Firefox, seems to be working for me. Actually, the history looks a bit better in Firefox as well IMO.

I've got a new commit in the same repo I linked above if you want to check it out!

**Comment by amitness** [comment]
@kitlawes I merged @andrewmbyrd's PR for the history table. Can you try it out once on Firefox. Then we can work on how to merge your PR #19 since there is merge conflicts now.

**Comment by kot91** [comment]
@amitness the current dev branch works properly in firefox with regard to storing data in the history table. I'll check out the conflicts now.

**Comment by amitness** [comment]
@kot91 Thanks. You've been a great help.
